# Generated by Django 2.1.5 on 2021-11-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cart_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
